# Generated by Django 5.0.3 on 2024-03-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('event_time', models.BigIntegerField()),
                ('symbol', models.CharField(max_length=100)),
                ('trade_id', models.BigIntegerField()),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('buy_order_id', models.BigIntegerField()),
                ('sell_order_id', models.BigIntegerField()),
                ('trade_completed_time', models.BigIntegerField()),
                ('is_maker', models.BooleanField()),
                ('is_taker', models.BooleanField()),
            ],
            options={
                'db_table': 'trade',
            },
        ),
    ]
