# Generated by Django 5.0.3 on 2024-03-30 14:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
